return function()
	local icons = {
		ui = require("modules.utils.icons").get("ui"),
		misc = require("modules.utils.icons").get("misc"),
	}

	require("which-key").setup({
		plugins = {
			presets = {
				operators = false,
				motions = false,
				text_objects = false,
				windows = false,
				nav = false,
				z = true,
				g = true,
			},
		},
		icons = {
			breadcrumb = icons.ui.Separator,
			separator = icons.misc.Vbar,
			group = icons.misc.Add,
		},
		window = {
			border = "none",
			position = "bottom",
			margin = { 1, 0, 1, 0 },
			padding = { 1, 1, 1, 1 },
			winblend = 0,
		},
	})

	require("which-key").register({
		["<leader>"] = {
			b = {
				name = "Bufferline commands",
				d = "buffer: Sort by directory",
				e = "buffer: Sort by extension",
			},
			c = {
				name = "Trouble commands",
				a = { mode = { "n", "v" }, "lsp: Code action" },
				d = "lsp: Show document diagnostics",
				i = "lsp: Show incoming calls",
				o = "lsp: Show outgoing calls",
				w = "lsp: Show workspace diagnostics",
				q = "lsp: Show quickfix list",
				l = "lsp: Show loclist",
				r = "lsp: Show lsp references",
			},
			d = {
				name = "Dap commands",
				b = "debug: Set breakpoint with condition",
				B = "debug: List breakpoints",
				c = "debug: Run to cursor",
				d = "debug: Terminate debug session",
				i = "debug: Step into",
				l = "debug: Do last run again",
				o = "debug: Step out",
				O = "debug: Open repl",
				r = "debug: Run/Continue",
				R = "debug: Start Lua debugger",
				v = "debug: Step over",
			},
			D = "git: Show diff",
			f = {
				name = "Telescope commands",
				p = "find: Project",
				w = "find: Word",
				r = "find: File by frecency",
				k = "find: Keymaps",
				s = "find: Word under cursor",
				d = "find: Session",
				e = "find: File by history",
				c = "ui: Change colorscheme",
				z = "edit: Change cwd using zoxide",
				f = "find: File under cwd",
				g = "find: File under current git directory",
				t = "find: Open filetree browser",
				b = "find: Buffer opened",
				h = "find: Nvim help tags",
				n = "edit: New file",
			},
			g = "git: Toggle lazygit",
			G = "git: Toggle fugitive",
			j = "jump: Goto line",
			k = "jump: Goto line",
			l = {
				name = "LSP commands",
				d = "lsp: Show line disgnostics",
				i = "lsp: LSP Info",
				r = "lsp: LSP Restart",
				p = "lsp: LSP Stop",
				s = "lsp: LSP Start",
			},
			n = {
				name = "NvimTree commands",
				f = "filetree: NvimTree find file",
				r = "filetree: NvimTree refresh",
			},
			o = "edit: Toggle spell check",
			p = {
				{ mode = "x", "edit: Replacement using blackhole reg" },

				name = "Package commands",
				h = "package: Show",
				s = "package: Sync",
				i = "package: Install",
				c = "package: Check",
				d = "package: Debug",
				l = "package: Log",
				p = "package: Profile",
				r = "package: Restore",
				x = "package: Clean",
				u = "package: Update",
			},
			r = {
				{ mode = "n", "tool: Execute current line" },
				{ mode = "v", "tool: Execute current selection" },
			},
			s = {
				name = "Session commands",
				s = "sesson: Save session",
				l = "sesson: Load current",
				d = "sesson: Delete session",
			},
			u = "edit: Show undo history",
			w = "jump: Goto word",
		},
		g = {
			name = "LSP commands",
			d = "lsp: Preview definition",
			D = "lsp: Goto definition",
			ea = "edit: Align with delimiter",
			h = "lsp: Show reference(s)",
			o = "lsp: Toggle outline",
			r = "lsp: Rename in file range",
			R = "lsp: Rename in project range",
			s = "lsp: Signature help",
			t = "lsp: Toggle trouble list",
			p = {
				name = "Git commands",
				P = "git: Push",
				p = "git: Pull",
			},
			["["] = "lsp: Prev diagnostic",
			["]"] = "lsp: Next diagnostic",
		},
		-- Core mappings
		["<S-Tab>"] = "edit: Toggle code fold",
		["<C-s>"] = "edit: Save file",
		Y = "edit: Yank text to EOL",
		D = "edit: Delete text to EOL",
		n = "edit: Next search result",
		N = "edit: Prev search result",
		J = {
			{ mode = "n", "edit: Join next line" },
			{ mode = "v", "edit: Move this line down" },
		},
		["<C-h>"] = {
			{ mode = "n", "window: Focus shift left" },
			{ mode = "c", "edit: Delete one char" },
		},
		["<A-o>"] = "window: Close current split",
		["<C-l>"] = "window: Focus shift right",
		["<C-j>"] = "window: Focus shift down",
		["<C-k>"] = "window: Focus shift up",
		["<A-[>"] = "window: Resize -5 vertically",
		["<A-]>"] = "window: Resize +5 vertically",
		["<A-;>"] = "window: Resize -2 horizontally",
		["<A-'>"] = "window: Resize +2 horizontally",
		["<Up>"] = "window: Resize +1 horizontally",
		["<Down>"] = "window: Resize -1 horizontally",
		["<Left>"] = "window: Resize +2 vertically",
		["<Right>"] = "window: Resize -2 vertically",
		["<C-q>"] = { mode = { "n", "i" }, "edit: Save file and quit" },
		["<A-S-q>"] = "edit: Force quit",
		["+"] = "edit: Increment under cursor",
		["-"] = "edit: Decrement under cursor",
		["<C-a>"] = {
			{ mode = { "n", "x" }, "edit: Select all" },
			{ mode = "c", "edit: Far left" },
			{ mode = "i", "edit: Move cursor to line start" },
		},
		["tn"] = "tab: Create a new window",
		["tk"] = "tab: Move to next window",
		["tj"] = "tab: Move to previous window",
		["to"] = "tab: Only keep current window",
		["<C-u>"] = { mode = "i", "edit: Delete previous block" },
		["<C-b>"] = { mode = { "c", "i" }, "edit: Move cursor one char left" },
		["<C-f>"] = { mode = "c", "edit: Right" },
		["<C-e>"] = { mode = "c", "edit: Far right" },
		["<C-d>"] = { mode = "c", "edit: Delete one char" },
		["<C-t>"] = { mode = "c", "edit: Complete path of parent folder" },
		K = {
			{ mode = "n", "lsp: Show doc" },
			{ mode = "v", "edit: Move this line up" },
		},
		["<"] = { mode = "v", "edit: Decrease indent (1L)" },
		[">"] = { mode = "v", "edit: Increase indent (1L)" },

		-- UI
		["gb"] = "buffer: Pick current buffer",
		["<A-q>"] = "buffer: Close",
		["<A-p>"] = "buffer: Pin current buffer",
		["<A-k>"] = "buffer: Cycle Next",
		["<A-j>"] = "buffer: Cycle Prev",
		["<A-S-k>"] = "buffer: Move current to next",
		["<A-S-j>"] = "buffer: Move current to prev",
		["<A-1>"] = "buffer: Goto buffer 1",
		["<A-2>"] = "buffer: Goto buffer 2",
		["<A-3>"] = "buffer: Goto buffer 3",
		["<A-4>"] = "buffer: Goto buffer 4",
		["<A-5>"] = "buffer: Goto buffer 5",
		["<A-6>"] = "buffer: Goto buffer 6",
		["<A-7>"] = "buffer: Goto buffer 7",
		["<A-8>"] = "buffer: Goto buffer 8",
		["<A-9>"] = "buffer: Goto buffer 9",

		-- LSP
		["<A-t>"] = "lsp: Toggle outline",
		["n|gs"] = "lsp: Signature help",
		["n|gr"] = "lsp: Rename in file range",
		["n|gR"] = "lsp: Rename in project range",
		["n|K"] = "lsp: Show doc",
		["nv|ga"] = "lsp: Code action for cursor",
		["n|gd"] = "lsp: Preview definition",
		["n|gD"] = "lsp: Goto definition",
		["n|gh"] = "lsp: Show reference",

		-- Terminals
		["<A-w>"] = { mode = "t", "terminal: Back to normal mode" },
		["<A-d>"] = { mode = { "n", "i", "t" }, "terminal: Toggle float" },
		["<A-\\>"] = { mode = { "n", "i", "t" }, "terminal: Toggle horizontal" },
		["<A-S-\\>"] = { mode = { "n", "i", "t" }, "terminal: Toggle vertical" },
		["<F5>"] = { mode = { "n", "i", "t" }, "terminal: Toggle vertical" },

		-- Misc keymaps
		["<F6>"] = "debug: Run/Continue",
		["<F7>"] = "debug: Terminate debug session",
		["<F8>"] = "debug: Toggle breakpoint",
		["<F9>"] = "debug: Step into",
		["<F10>"] = "debug: Step out",
		["<F11>"] = "debug: Step over",
		["<F12>"] = "tool: Markdown preview",
		["<C-n>"] = "filetree: Toggle",
		["<C-S-s>"] = "edit: Save file using sudo",
		["<A-h>"] = "edit: Goto begin of pair",
		["<A-l>"] = "edit: Goto end of pair",
		["<leader>c"] = "jump: Goto one char",
		["<leader>cc"] = "jump: Goto two chars",
		["<leader><leader>D"] = "git: Close diff",
	})
end
