return function()
	local icons = {
		ui = require("modules.utils.icons").get("ui"),
		misc = require("modules.utils.icons").get("misc"),
	}

	require("which-key").setup({
		preset = "classic",
		delay = vim.o.timeoutlen,
		triggers = {
			{ "<auto>", mode = "nixso" },
		},
		win = {
			border = "none",
			padding = { 1, 2 },
			wo = { winblend = 0 },
		},
		plugins = {
			marks = true,
			registers = true,
			spelling = {
				enabled = true,
				suggestions = 20,
			},
			presets = {
				motions = false,
				operators = false,
				text_objects = true,
				windows = true,
				nav = true,
				z = true,
				g = true,
			},
		},
		icons = {
			group = "",
			rules = false,
			colors = false,
			separator = icons.misc.Vbar,
			breadcrumb = icons.ui.Separator,
			keys = {
				C = "C-",
				M = "A-",
				S = "S-",
				BS = "<BS> ",
				CR = "<CR> ",
				NL = "<NL> ",
				Esc = "<Esc> ",
				Tab = "<Tab> ",
				Up = "<Up> ",
				Down = "<Down> ",
				Left = "<Left> ",
				Right = "<Right> ",
				Space = "<Space> ",
				ScrollWheelUp = "<ScrollWheelUp> ",
				ScrollWheelDown = "<ScrollWheelDown> ",
			},
		},
		spec = {
			-- <leader> stuff
			--- Buffers
			{ "<leader>b", group = "󰓩 Buffers" },
			{ "<leader>bd", desc = "buffer: Sort by directory" },
			{ "<leader>be", desc = "buffer: Sort by extension" },
			--- Spell check
			{ "<leader>c", desc = "edit: Toggle spell check" },
			--- Debug
			{ "<leader>d", group = " Debug" },
			{ "<leader>db", desc = "debug: Set breakpoint with condition" },
			{ "<leader>dB", desc = "debug: List breakpoints" },
			{ "<leader>dc", desc = "debug: Run to cursor" },
			{ "<leader>dd", desc = "debug: Close debug panels" },
			{ "<leader>di", desc = "debug: Step into" },
			{ "<leader>dl", desc = "debug: Do last run again" },
			{ "<leader>dn", desc = "debug: Use this nvim instance as server" },
			{ "<leader>do", desc = "debug: Step out" },
			{ "<leader>dO", desc = "debug: Open repl" },
			{ "<leader>dr", desc = "debug: Run/Continue" },
			{ "<leader>dR", desc = "debug: Start a Lua debugger" },
			{ "<leader>dt", desc = "debug: Terminate the current session" },
			{ "<leader>dv", desc = "debug: Step over" },
			--- Fuzzy finder
			{ "<leader>f", group = " Telescope / Fuzzy Finder" },
			{ "<leader>fa", desc = "find: Nvim automatic commands" },
			{ "<leader>fb", desc = "find: Open buffer(s)" },
			{ "<leader>fc", desc = "ui: Change colorscheme" },
			{ "<leader>fd", desc = "find: Session" },
			{ "<leader>fe", desc = "find: File using ShaDa" },
			{ "<leader>ff", desc = "find: File under cwd" },
			{ "<leader>fg", desc = "find: File managed by git" },
			{ "<leader>fh", desc = "find: Nvim highlight groups" },
			{ "<leader>fi", desc = "find: Open a file browser" },
			{ "<leader>fk", desc = "find: Keymaps" },
			{ "<leader>fn", desc = "edit: New empty file" },
			{ "<leader>fo", desc = "find: Nvim options" },
			{ "<leader>fp", desc = "find: Project" },
			{ "<leader>fr", desc = "find: File by frecency" },
			{ "<leader>fR", desc = "find: Open previous picker" },
			{ "<leader>fs", desc = "find: Word under cursor", mode = "n" },
			{ "<leader>fs", desc = "find: Current selection", mode = "v" },
			{ "<leader>ft", desc = "find: Todo comments" },
			{ "<leader>fw", desc = "find: Word" },
			{ "<leader>fz", desc = "edit: Change cwd using zoxide" },
			--- Git
			{ "<leader>g", group = "󰊢 Git" },
			{ "<leader>gd", desc = "git: Show diff" },
			{ "<leader>gD", desc = "git: Close diff" },
			{ "<leader>gf", desc = "git: Show current file's history" },
			{ "<leader>gF", desc = "git: Close current file's history" },
			{ "<leader>gG", desc = "git: Toggle fugitive" },
			{ "<leader>gg", desc = "git: Toggle lazygit" },
			--- Jump
			{ "<leader>j", desc = "jump: Goto line" },
			{ "<leader>k", desc = "jump: Goto line" },
			{ "<leader>o", desc = "jump: Goto one char" },
			{ "<leader>O", desc = "jump: Goto two chars" },
			{ "<leader>w", desc = "jump: Goto word" },
			--- LSP
			{ "<leader>l", group = "󱜙 LSP" },
			{ "<leader>ld", desc = "lsp: Show document diagnostics" },
			{ "<leader>lh", desc = "lsp: Toggle inlay hint" },
			{ "<leader>li", desc = "lsp: Info" },
			{ "<leader>lp", desc = "lsp: Show project diagnostics" },
			{ "<leader>lr", desc = "lsp: Restart" },
			{ "<leader>lS", desc = "lsp: Start" },
			{ "<leader>ls", desc = "lsp: Stop" },
			{ "<leader>lv", desc = "lsp: Toggle virtual lines" },
			{ "<leader>lw", desc = "lsp: Show workspace diagnostics" },
			{ "<leader>lx", desc = "lsp: Show line disgnostics" },
			--- File tree
			{ "<leader>n", group = " File Tree" },
			{ "<leader>nf", desc = "filetree: NvimTree find file" },
			{ "<leader>nr", desc = "filetree: NvimTree refresh" },
			--- Package
			{ "<leader>p", group = " Package" },
			{ "<leader>pc", desc = "package: Check" },
			{ "<leader>pd", desc = "package: Debug" },
			{ "<leader>ph", desc = "package: Show" },
			{ "<leader>pi", desc = "package: Install" },
			{ "<leader>pl", desc = "package: Log" },
			{ "<leader>pp", desc = "package: Profile" },
			{ "<leader>pr", desc = "package: Restore" },
			{ "<leader>ps", desc = "package: Sync" },
			{ "<leader>pu", desc = "package: Update" },
			{ "<leader>px", desc = "package: Clean" },
			--- QuickFix
			{ "<leader>q", group = " QuickFix" },
			{ "<leader>qa", desc = "qf: Previous item above the current line" },
			{ "<leader>qb", desc = "qf: Next item below the current line" },
			{ "<leader>qc", desc = "qf: Close" },
			{ "<leader>qf", desc = "qf: First item" },
			{ "<leader>ql", desc = "qf: Last item" },
			{ "<leader>qn", desc = "qf: Next item" },
			{ "<leader>qo", desc = "qf: Open" },
			{ "<leader>qp", desc = "qf: Previous item" },
			{ "<leader>qq", desc = "qf: Close" },
			--- SnipRun
			{ "<leader>r", desc = "tool: Execute current line", mode = "n" },
			{ "<leader>r", desc = "tool: Execute current selection", mode = "v" },
			--- Sessions
			{ "<leader>s", group = " Sessions" },
			{ "<leader>sd", desc = "session: Delete current" },
			{ "<leader>sl", desc = "session: Load current" },
			{ "<leader>sr", desc = "session: Goto root directory" },
			{ "<leader>ss", desc = "session: Save current" },
			{ "<leader>st", desc = "session: Toggle current" },
			--- Tab pages
			{ "<leader>t", group = " Tab Pages" },
			{ "<leader>tc", desc = "tab: Close current tab" },
			{ "<leader>td", desc = "tab: Close current tab" },
			{ "<leader>tj", desc = "tab: Move to previous tab" },
			{ "<leader>tk", desc = "tab: Move to next tab" },
			{ "<leader>tN", desc = "tab: Create a new tab" },
			{ "<leader>tn", desc = "tab: Move to next tab" },
			{ "<leader>to", desc = "tab: Only keep current tab" },
			{ "<leader>tp", desc = "tab: Move to previous tab" },
			--- Undo
			{ "<leader>u", desc = "edit: Show undo history" },

			-- UI/UX
			{ "<A-q>", desc = "buffer: Close" },
			{ "<A-j>", desc = "buffer: Cycle Prev" },
			{ "<A-k>", desc = "buffer: Cycle Next" },
			{ "<A-p>", desc = "buffer: Pin current buffer" },
			{ "<A-1>", desc = "buffer: Goto buffer 1" },
			{ "<A-2>", desc = "buffer: Goto buffer 2" },
			{ "<A-3>", desc = "buffer: Goto buffer 3" },
			{ "<A-4>", desc = "buffer: Goto buffer 4" },
			{ "<A-5>", desc = "buffer: Goto buffer 5" },
			{ "<A-6>", desc = "buffer: Goto buffer 6" },
			{ "<A-7>", desc = "buffer: Goto buffer 7" },
			{ "<A-8>", desc = "buffer: Goto buffer 8" },
			{ "<A-9>", desc = "buffer: Goto buffer 9" },
			{ "<A-S-j>", desc = "buffer: Move current to prev" },
			{ "<A-S-k>", desc = "buffer: Move current to next" },
			{ "<A-'>", desc = "window: Resize +2 horizontally" },
			{ "<A-;>", desc = "window: Resize -2 horizontally" },
			{ "<A-[>", desc = "window: Resize -5 vertically" },
			{ "<A-]>", desc = "window: Resize +5 vertically" },
			{ "<C-j>", desc = "window: Focus shift down" },
			{ "<C-l>", desc = "window: Focus shift right" },
			{ "<C-h>", desc = "window: Focus shift left", mode = { "n", "t" } },
			{ "<C-k>", desc = "window: Focus shift up", mode = { "n", "t" } },
			{ "<Up>", desc = "window: Resize +1 horizontally" },
			{ "<Down>", desc = "window: Resize -1 horizontally" },
			{ "<Left>", desc = "window: Resize +2 vertically" },
			{ "<Right>", desc = "window: Resize -2 vertically" },

			-- Utilities
			{ "g", group = "󰢩 Miscellaneous / Utils" },
			--- LSP
			{ "go", desc = "lsp: Toggle outline" },
			{ "gD", desc = "lsp: Goto definition" },
			{ "g[", desc = "lsp: Prev diagnostic" },
			{ "g]", desc = "lsp: Next diagnostic" },
			{ "gh", desc = "lsp: Show reference(s)" },
			{ "gr", desc = "lsp: Rename in file range" },
			{ "gd", desc = "lsp: Preview definition(s)" },
			{ "gm", desc = "lsp: Show implementation(s)" },
			{ "ga", desc = "lsp: Code action", mode = { "n", "v" } },
			{ "gR", desc = "lsp: Rename in project range" },
			{ "gt", desc = "lsp: Preview type definition(s)" },
			--- Alignments
			{ "ge", group = "󰝔 Alignments" },
			{ "geA", desc = "edit: Align text interactively (preview enabled)" },
			{ "gea", desc = "edit: Align text interactively" },
			--- LSP call hierarchy
			{ "gl", group = "󱜙 LSP Call Hierarchy" },
			{ "gli", desc = "lsp: Show incoming calls" },
			{ "glo", desc = "lsp: Show outgoing calls" },
			--- Git
			{ "gp", group = "󰊢 Git" },
			{ "gpl", desc = "git: Pull" },
			{ "gps", desc = "git: Push" },

			-- Terminals
			{ "<A-q>", desc = "terminal: Back to normal mode", mode = "t" },
			{
				mode = { "i", "n", "t" },
				{ "<A-d>", desc = "terminal: Toggle float" },
				{ "<F5>", desc = "terminal: Toggle vertical" },
				{ "<A-S-\\>", desc = "terminal: Toggle vertical" },
				{ "<A-\\>", desc = "terminal: Toggle horizontal" },
			},

			-- Miscellaneous
			{ "K", desc = "lsp: Show doc" },
			{ "J", desc = "edit: Join next line" },
			{ "Y", desc = "edit: Yank text to EOL" },
			{ "D", desc = "edit: Delete text to EOL" },
			{ "N", desc = "edit: Prev search result" },
			{ "n", desc = "edit: Next search result" },
			{ "-", desc = "edit: Decrement number under cursor" },
			{ "+", desc = "edit: Increment number under cursor" },
			{ "<Esc>", desc = "edit: Clear search highlight" },
			{ "<S-Tab>", desc = "edit: Toggle code fold" },
			{ "<A-f>", desc = "formatter: Toggle format on save" },
			{ "<A-S-q>", desc = "edit: Force quit without saving" },
			{ "<A-S-u>", desc = "edit: Toggle the undofile config" },
			{ "<C-s>", desc = "edit: Save file" },
			{ "<C-n>", desc = "filetree: Toggle" },
			{ "<C-S-s>", desc = "edit: Save file using sudo" },
			{ "<C-a>", desc = "edit: Select all", mode = { "n", "x" } },
			{ "<C-q>", desc = "edit: Save file and quit", mode = { "i", "n" } },
			{ "<C-b>", desc = "edit: Move cursor one char left", mode = { "c", "i" } },
			{ "<F1>", desc = "tool: toggle markdown preview within nvim" },
			{ "<F6>", desc = "debug: Run/Continue" },
			{ "<F7>", desc = "debug: Terminate debug session" },
			{ "<F8>", desc = "debug: Toggle breakpoint" },
			{ "<F9>", desc = "debug: Step into" },
			{ "<F10>", desc = "debug: Step out" },
			{ "<F11>", desc = "debug: Step over" },
			{ "<F12>", desc = "tool: Markdown preview" },

			-- Convenience mappings
			--- Treehopper
			{ "m", desc = "jump: Operate across the syntax tree", mode = { "o", "v" } },
			--- Insert mode
			{
				mode = { "i" },
				{ "<A-h>", desc = "edit: Goto begin of pair" },
				{ "<A-l>", desc = "edit: Goto end of pair" },
				{ "<C-a>", desc = "edit: Move cursor to line start" },
				{ "<C-u>", desc = "edit: Delete previous block" },
			},
			--- Command mode
			{
				mode = { "c" },
				{ "<C-f>", desc = "edit: Right" },
				{ "<C-a>", desc = "edit: Far left" },
				{ "<C-e>", desc = "edit: Far right" },
				{ "<C-d>", desc = "edit: Delete one char" },
				{ "<C-h>", desc = "edit: Delete one char" },
				{ "%%", desc = "edit: Complete parent folder path" },
				{ "<C-S-f>", desc = "edit: Open command-line window" },
			},
			--- Visual mode
			{
				mode = { "v" },
				{ "<", desc = "edit: Decrease indentation (1L)" },
				{ ">", desc = "edit: Increase indentation (1L)" },
				{ "J", desc = "edit: Move this line down" },
				{ "K", desc = "edit: Move this line up" },
			},
			--- Visual and Select mode
			{
				mode = { "x" },
				{ "<leader>p", desc = "edit: Replacement using blackhole reg" },
			},
		},
	})
end
