name: lint code
on: [push, pull_request]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lunarmodules/luacheck@v1
        with:
          args: . --std luajit --globals vim _debugging _buf_vtext _command_panel _flash_esc_or_noh _toggle_lazygit --max-line-length 150 --no-config
